//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34003
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sniptfisher.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sniptfisher.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sniptfisher.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a share.
        /// </summary>
        public static string DetailPage_ShareAppBarIconButton {
            get {
                return ResourceManager.GetString("DetailPage_ShareAppBarIconButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a public.
        /// </summary>
        public static string MainPage_PublicPanoramaItem {
            get {
                return ResourceManager.GetString("MainPage_PublicPanoramaItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a search.
        /// </summary>
        public static string MainPage_SearchAppBarIconButton {
            get {
                return ResourceManager.GetString("MainPage_SearchAppBarIconButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a settings.
        /// </summary>
        public static string MainPage_SettingsAppBarMenuItem {
            get {
                return ResourceManager.GetString("MainPage_SettingsAppBarMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Searching.
        /// </summary>
        public static string SearchPage_HintSearchTextBlock {
            get {
                return ResourceManager.GetString("SearchPage_HintSearchTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SHARE.
        /// </summary>
        public static string SearchPage_PageTitle {
            get {
                return ResourceManager.GetString("SearchPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Searching....
        /// </summary>
        public static string SearchPage_SystemTrayText {
            get {
                return ResourceManager.GetString("SearchPage_SystemTrayText", resourceCulture);
            }
        }
    }
}
